[versions]
agp = "9.0.1"
gson = "2.13.2"
guava = "33.5.0-android"
hiltAndroid = "2.59.2"
hiltCompiler = "2.59.2"
junit = "4.13.2"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.4"
constraintlayout = "2.2.1"
preference = "1.2.1"
annotation = "1.9.1"
lifecycleLivedataKtx = "2.10.0"
lifecycleViewmodelKtx = "2.10.0"
firebaseBom = "34.9.0"
firebaseAi = "17.9.0"
reactiveStreams = "1.0.4"
workRuntime = "2.11.1"
hiltWork = "1.3.0"
junitExt = "1.3.0"
localagentsFc = "0.1.0"

[libraries]
firebase-ai = { module = "com.google.firebase:firebase-ai", version.ref = "firebaseAi" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-firebase-database = { module = "com.google.firebase:firebase-database" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
reactive-streams = { module = "org.reactivestreams:reactive-streams", version.ref = "reactiveStreams" }
work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "workRuntime" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
localagents-fc = { group = "com.google.ai.edge.localagents", name = "localagents-fc", version.ref = "localagentsFc" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version = "4.4.4" }
hilt-android    = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
